[buildPlans.IosevkaCustom]
exportGlyphNames = true
family           = "Iosevka Custom"
noCvSs           = false
serifs           = "sans"
spacing          = "term"
#xHeight          = 400 # Font height

[buildPlans.IosevkaCustom.metricOverride]
leading = 1100 # Line height

[buildPlans.IosevkaCustom.weights.Regular]
css   = 400
menu  = 400
shape = 400

[buildPlans.IosevkaCustom.weights.Book]
css   = 450
menu  = 450
shape = 450

[buildPlans.IosevkaCustom.weights.Bold]
css   = 700
menu  = 700
shape = 700

[buildPlans.IosevkaCustom.widths.Normal]
css   = "normal"
menu  = 5
shape = 500

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
css   = "normal"
menu  = "upright"
shape = "upright"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 10.4
css   = "italic"
menu  = "italic"
shape = "italic"
