[buildPlans.IosevkaCustom]
exportGlyphNames = true
family           = "Iosevka Custom"
noCvSs           = false
serifs           = "sans"
spacing          = "fontconfig-mono"
#xHeight          = 400 # Font height

[buildPlans.IosevkaCustom.metricOverride]
leading = 1100 # Line height

[buildPlans.IosevkaCustom.variants.design]
brace   = "curly-flat-boundary"
m       = "earless-corner-double-arch-short-leg-serifless"
paren   = "large-contour"
percent = "rings-continuous-slash"
seven   = "straight-serifed"
zero    = "dotted"

[buildPlans.IosevkaCustom.ligations]
inherits = "dlig"

[buildPlans.IosevkaCustom.weights.Regular]
css   = 400
menu  = 400
shape = 400

[buildPlans.IosevkaCustom.weights.Bold]
css   = 700
menu  = 700
shape = 700

[buildPlans.IosevkaCustom.widths.Normal]
css   = "normal"
menu  = 5
shape = 500

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
css   = "normal"
menu  = "upright"
shape = "upright"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 10.5
css   = "italic"
menu  = "italic"
shape = "italic"
