[buildPlans.IosevkaCustom]
exportGlyphNames = true
family           = "Iosevka Custom"
noCvSs           = false
serifs           = "sans"
spacing          = "term"

[buildPlans.IosevkaCustom.variants.design]
asterisk             = "penta-low"
brace                = "curly-flat-boundary"
cent                 = "bar-interrupted"
dollar               = "interrupted"
guillemet            = "curly"
lig-double-arrow-bar = "without-notch"
lig-neq              = "more-slanted-dotted"
lig-single-arrow-bar = "without-notch"
m                    = "short-leg-serifless"
paren                = "large-contour"
percent              = "rings-continuous-slash"
punctuation-dot      = "square"
question             = "smooth"
seven                = "straight-serifless-crossbar"
zero                 = "dotted"

[buildPlans.IosevkaCustom.variants.italic]
brace                = "curly-flat-boundary"
cent                 = "bar-interrupted"
dollar               = "interrupted"
lig-double-arrow-bar = "without-notch"
lig-neq              = "more-slanted-dotted"
lig-single-arrow-bar = "without-notch"
m                    = "short-leg-serifless"
paren                = "large-contour"
percent              = "rings-continuous-slash"
question             = "smooth"
zero                 = "dotted"

[buildPlans.IosevkaCustom.variants.oblique]
brace                = "curly-flat-boundary"
cent                 = "bar-interrupted"
dollar               = "interrupted"
lig-double-arrow-bar = "without-notch"
lig-neq              = "more-slanted-dotted"
lig-single-arrow-bar = "without-notch"
m                    = "short-leg-serifless"
paren                = "large-contour"
percent              = "rings-continuous-slash"
question             = "smooth"
seven                = "straight-serifless-crossbar"
zero                 = "dotted"

[buildPlans.IosevkaCustom.ligations]
inherits = "dlig"

[buildPlans.IosevkaCustom.weights.Light]
css   = 300
menu  = 300
shape = 300

[buildPlans.IosevkaCustom.weights.Regular]
css   = 400
menu  = 400
shape = 400

[buildPlans.IosevkaCustom.weights.Retina]
css   = 450
menu  = 450
shape = 450

[buildPlans.IosevkaCustom.weights.Medium]
css   = 500
menu  = 500
shape = 500

[buildPlans.IosevkaCustom.weights.SemiBold]
css   = 600
menu  = 600
shape = 600

[buildPlans.IosevkaCustom.weights.Bold]
css   = 700
menu  = 700
shape = 700

[buildPlans.IosevkaCustom.weights.ExtraBold]
css   = 800
menu  = 800
shape = 800

[buildPlans.IosevkaCustom.widths.Normal]
css   = "normal"
menu  = 5
shape = 500

[buildPlans.IosevkaCustom.widths.Extended]
css   = "expanded"
menu  = 7
shape = 600

[buildPlans.IosevkaCustom.widths.SemiCondensed]
css   = "semi-condensed"
menu  = 4
shape = 456

[buildPlans.IosevkaCustom.widths.SemiExtended]
css   = "semi-expanded"
menu  = 6
shape = 548
