[buildPlans.IosevkaCustom]
exportGlyphNames = true
family           = "Iosevka Custom"
noCvSs           = false
serifs           = "sans"
spacing          = "term"
xHeight          = 400              # Font height

[buildPlans.IosevkaCustom.metricOverride]
leading = 1150 # Line height

[buildPlans.IosevkaCustom.variants.design]
asterisk             = "penta-low"
brace                = "curly-flat-boundary"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"
m                    = "short-leg-serifless"
paren                = "large-contour"
percent              = "rings-continuous-slash"
zero                 = "dotted"

[buildPlans.IosevkaCustom.variants.italic]
asterisk             = "penta-low"
brace                = "curly-flat-boundary"
k                    = "symmetric-connected-serifless"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"
m                    = "short-leg-serifless"
paren                = "large-contour"
percent              = "rings-continuous-slash"
zero                 = "dotted"

[buildPlans.IosevkaCustom.weights.Light]
css   = 300
menu  = 300
shape = 300

[buildPlans.IosevkaCustom.weights.Regular]
css   = 400
menu  = 400
shape = 400

[buildPlans.IosevkaCustom.weights.Book]
css   = 450
menu  = 450
shape = 450

[buildPlans.IosevkaCustom.weights.Medium]
css   = 500
menu  = 500
shape = 500

[buildPlans.IosevkaCustom.weights.Bold]
css   = 700
menu  = 700
shape = 700

[buildPlans.IosevkaCustom.widths.Normal]
css   = "normal"
menu  = 5
shape = 500

[buildPlans.IosevkaCustom.widths.SemiExtended]
css   = "semi-expanded"
menu  = 6
shape = 548

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
css   = "normal"
menu  = "upright"
shape = "upright"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 9.4
css   = "italic"
menu  = "italic"
shape = "italic"
